title:               "lxmrc"
tagline:             "Ruby developer based in Melbourne"
url:                 https://lxmrc.github.io
date_format: "%e %B %Y"
permalinks: pretty

excerpt_separator:   <!--more-->
twitter_username:   "lxmrc"

include: ['_pages']

pages_list:
  about: '/about.html'
  github: 'https://github.com/lxmrc'
  til: '/til.html'

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              Alex
  url:               https://twitter.com/lxmrc
  email:             alex_mercea@protonmail.com

markdown: kramdown
kramdown:
  input: GFM
