title:               "lxmrc"
url:                 https://lxmrc.com
date_format: "%e %B %Y"
permalinks: pretty

excerpt_separator:   <!--more-->
twitter_username:   "lxmrc"

include: ['_pages']

pages_list:
  about: '/about.html'
  links: '/links.html'

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              Alex
  url:               https://twitter.com/lxmrc
  email:             alex@protonmail.com

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
